# Generated by Django 4.2.5 on 2023-11-16 07:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_threshold', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_detections', to='YoloObjectDetectionAPI.imageupload')),
            ],
        ),
        migrations.CreateModel(
            name='Detections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('x_min', models.FloatField()),
                ('x_max', models.FloatField()),
                ('y_min', models.FloatField()),
                ('y_max', models.FloatField()),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('object_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='YoloObjectDetectionAPI.objectdetection')),
            ],
        ),
    ]
