# Generated by Django 4.2.5 on 2023-11-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YoloObjectDetectionAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='object_detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='YoloObjectDetectionAPI.imageupload'),
        ),
        migrations.DeleteModel(
            name='ObjectDetection',
        ),
    ]
